import os
import folder_paths

# Ścieżka do folderu z węzłem
node_dir = os.path.dirname(os.path.abspath(__file__))

# Dodaj folder z węzłem do ścieżki ComfyUI
folder_paths.add_model_folder_path("custom_nodes", node_dir)

# Załaduj skrypt JavaScript
WEB_DIRECTORY = os.path.join(node_dir, "js")

# Importowanie klas węzłów
from .HyvidSwitcher import HYVID_SWITCHER_NODE_CLASS_MAPPINGS, HYVID_SWITCHER_NODE_DISPLAY_NAME_MAPPINGS
from .midi_analyzer import MIDI_ANALYZER_NODE_CLASS_MAPPINGS, MIDI_ANALYZER_NODE_DISPLAY_NAME_MAPPINGS
from .midi_to_frame_sequences import MIDI_TO_FRAME_SEQUENCES_NODE_CLASS_MAPPINGS, MIDI_TO_FRAME_SEQUENCES_NODE_DISPLAY_NAME_MAPPINGS
from .video_sequencer import VIDEO_SEQUENCER_NODE_CLASS_MAPPINGS, VIDEO_SEQUENCER_NODE_DISPLAY_NAME_MAPPINGS
from .video_counter import VIDEO_COUNTER_NODE_CLASS_MAPPINGS, VIDEO_COUNTER_NODE_DISPLAY_NAME_MAPPINGS
from .image_sequence_from_batch import IMAGE_SEQUENCE_FROM_BATCH_NODE_CLASS_MAPPINGS, IMAGE_SEQUENCE_FROM_BATCH_NODE_DISPLAY_NAME_MAPPINGS
from .PathSwitcher import PATH_SWITCHER_NODE_CLASS_MAPPINGS, PATH_SWITCHER_NODE_DISPLAY_NAME_MAPPINGS

# Łączenie mapowań
NODE_CLASS_MAPPINGS = {
    **HYVID_SWITCHER_NODE_CLASS_MAPPINGS,
    **MIDI_ANALYZER_NODE_CLASS_MAPPINGS,
    **MIDI_TO_FRAME_SEQUENCES_NODE_CLASS_MAPPINGS,
    **VIDEO_SEQUENCER_NODE_CLASS_MAPPINGS,
    **VIDEO_COUNTER_NODE_CLASS_MAPPINGS,
    **IMAGE_SEQUENCE_FROM_BATCH_NODE_CLASS_MAPPINGS,
    **PATH_SWITCHER_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **HYVID_SWITCHER_NODE_DISPLAY_NAME_MAPPINGS,
    **MIDI_ANALYZER_NODE_DISPLAY_NAME_MAPPINGS,
    **MIDI_TO_FRAME_SEQUENCES_NODE_DISPLAY_NAME_MAPPINGS,
    **VIDEO_SEQUENCER_NODE_DISPLAY_NAME_MAPPINGS,
    **VIDEO_COUNTER_NODE_DISPLAY_NAME_MAPPINGS,
    **IMAGE_SEQUENCE_FROM_BATCH_NODE_DISPLAY_NAME_MAPPINGS,
    **PATH_SWITCHER_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]