from .HyvidSwitcher import HYVID_SWITCHER_NODE_CLASS_MAPPINGS, HYVID_SWITCHER_NODE_DISPLAY_NAME_MAPPINGS
from .midi_analyzer import MIDI_ANALYZER_NODE_CLASS_MAPPINGS, MIDI_ANALYZER_NODE_DISPLAY_NAME_MAPPINGS

# Łączenie mapowań klas węzłów i ich nazw wyświetlanych
NODE_CLASS_MAPPINGS = {
    **HYVID_SWITCHER_NODE_CLASS_MAPPINGS,
    **MIDI_ANALYZER_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **HYVID_SWITCHER_NODE_DISPLAY_NAME_MAPPINGS,
    **MIDI_ANALYZER_NODE_DISPLAY_NAME_MAPPINGS,
}